# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 335099435bbca3aa8e31d4f1e8a1c9ce87e6cc5ec9bb24e63de9e76f4b85661aa336b28b43b1086e66c671375f9b62ad215c8f7e258e24cbda83f464bb9ffe7c

test:
  secret_key_base: aae390f260318d7dd4ec5ff9e8a0c0390a8a3fdc84a24de1715c0e792bd8c6e618a6db6d882a810260723c49840e753d0931eade28db6e844d6516d80c6c7aff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
